pragma solidity ^0.8.0;

library ICookingItem {
    enum List {
        None,
        Raw_White_Meat,
        Apple,
        Carrot,
        Cabbage,
        Bell_Pepper,
        Chili_Pepper,
        Tomato,
        Onion,
        Flour,
        Corn,
        Meat,
        Steak,
        Egg,
        Mushroom,
        Milk,
        Water,
        Sea_Fish,
        Ocean_Fish,
        Turnip,
        Grapes,
        Black_Grapes,
        Red_Grapes,
        Strawberry,
        Cherry,
        Wine,
        Salt,
        Cacao,
        Chocolate,
        Butter,
        Sugar,
        Banana,
        Potato,
        Olive_Oil,
        Sunflower_Oil
    }
}
